# Generated by Django 2.1.2 on 2018-10-30 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('hosts', models.CharField(max_length=255)),
                ('drink', models.CharField(blank=True, max_length=255)),
                ('crawl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.Crawl')),
            ],
        ),
    ]
